Drop JRuby 9.4 from CI
Getting a weird error in CI for JRuby 9.4, looks like an internal
JRuby problem:

```
LoadError: load error: strscan -- java.lang.NoSuchMethodError: 'org.jruby.RubyClass org.jruby.RubyClass.defineClassUnder(org.jruby.runtime.ThreadContext, java.lang.String, org.jruby.RubyClass, org.jruby.runtime.ObjectAllocator)'
```

Specs pass on JRuby 10.0 and 9.2, so this doesn't appear to be an
issue with tilt. If the JRuby issue is fixed, this can be reverted.